import type { CreateAppInput } from './schemas.js';

export interface AppTemplate {
  id: string;
  name: string;
  description: string;
  category: 'web' | 'database' | 'storage' | 'monitoring' | 'devops' | 'productivity';
  icon: string; // emoji
  defaults: Omit<CreateAppInput, 'name' | 'subdomain' | 'domain' | 'tlsEnabled'>;
  docs?: string;
  requiredEnv?: string[]; // env vars the user must fill
}

export const TEMPLATES: AppTemplate[] = [
  // ── Web ──────────────────────────────────────────────────────────────────
  {
    id: 'nginx',
    name: 'Nginx',
    description: 'Serveur web statique haute performance.',
    category: 'web',
    icon: '🌐',
    docs: 'https://hub.docker.com/_/nginx',
    defaults: {
      type: 'docker-image',
      image: 'nginx',
      imageTag: 'alpine',
      ports: [{ containerPort: 80, protocol: 'TCP' }],
      envVars: [],
      volumes: [{ name: 'html', mountPath: '/usr/share/nginx/html', size: '1Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'CMS open-source le plus populaire au monde.',
    category: 'web',
    icon: '📝',
    docs: 'https://hub.docker.com/_/wordpress',
    requiredEnv: ['WORDPRESS_DB_HOST', 'WORDPRESS_DB_USER', 'WORDPRESS_DB_PASSWORD', 'WORDPRESS_DB_NAME'],
    defaults: {
      type: 'docker-image',
      image: 'wordpress',
      imageTag: 'latest',
      ports: [{ containerPort: 80, protocol: 'TCP' }],
      envVars: [
        { key: 'WORDPRESS_DB_HOST', value: 'mysql:3306' },
        { key: 'WORDPRESS_DB_USER', value: 'wordpress' },
        { key: 'WORDPRESS_DB_PASSWORD', value: 'changeme' },
        { key: 'WORDPRESS_DB_NAME', value: 'wordpress' },
      ],
      volumes: [{ name: 'data', mountPath: '/var/www/html', size: '5Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    description: 'Plateforme de blogging et publication moderne.',
    category: 'web',
    icon: '👻',
    docs: 'https://hub.docker.com/_/ghost',
    defaults: {
      type: 'docker-image',
      image: 'ghost',
      imageTag: 'alpine',
      ports: [{ containerPort: 2368, protocol: 'TCP' }],
      envVars: [
        { key: 'NODE_ENV', value: 'production' },
        { key: 'database__client', value: 'sqlite3' },
      ],
      volumes: [{ name: 'content', mountPath: '/var/lib/ghost/content', size: '5Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    description: 'Monitoring de disponibilité avec alertes.',
    category: 'monitoring',
    icon: '📊',
    docs: 'https://github.com/louislam/uptime-kuma',
    defaults: {
      type: 'docker-image',
      image: 'louislam/uptime-kuma',
      imageTag: '1',
      ports: [{ containerPort: 3001, protocol: 'TCP' }],
      envVars: [],
      volumes: [{ name: 'data', mountPath: '/app/data', size: '2Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Automatisation de workflows no-code / low-code.',
    category: 'productivity',
    icon: '🔗',
    docs: 'https://hub.docker.com/r/n8nio/n8n',
    defaults: {
      type: 'docker-image',
      image: 'n8nio/n8n',
      imageTag: 'latest',
      ports: [{ containerPort: 5678, protocol: 'TCP' }],
      envVars: [
        { key: 'N8N_BASIC_AUTH_ACTIVE', value: 'true' },
        { key: 'N8N_BASIC_AUTH_USER', value: 'admin' },
        { key: 'N8N_BASIC_AUTH_PASSWORD', value: 'changeme' },
      ],
      volumes: [{ name: 'data', mountPath: '/home/node/.n8n', size: '2Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    description: 'Gestionnaire de mots de passe compatible Bitwarden.',
    category: 'productivity',
    icon: '🔐',
    docs: 'https://github.com/dani-garcia/vaultwarden',
    defaults: {
      type: 'docker-image',
      image: 'vaultwarden/server',
      imageTag: 'latest',
      ports: [{ containerPort: 80, protocol: 'TCP' }],
      envVars: [
        { key: 'WEBSOCKET_ENABLED', value: 'true' },
        { key: 'SIGNUPS_ALLOWED', value: 'false' },
      ],
      volumes: [{ name: 'data', mountPath: '/data', size: '2Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'gitea',
    name: 'Gitea',
    description: 'Forge Git légère, auto-hébergée.',
    category: 'devops',
    icon: '🐙',
    docs: 'https://hub.docker.com/r/gitea/gitea',
    defaults: {
      type: 'docker-image',
      image: 'gitea/gitea',
      imageTag: 'latest',
      ports: [{ containerPort: 3000, protocol: 'TCP' }],
      envVars: [
        { key: 'GITEA__database__DB_TYPE', value: 'sqlite3' },
        { key: 'GITEA__server__DOMAIN', value: '' },
      ],
      volumes: [{ name: 'data', mountPath: '/data', size: '10Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    description: 'Suite collaborative : fichiers, calendrier, contacts.',
    category: 'productivity',
    icon: '☁️',
    docs: 'https://hub.docker.com/_/nextcloud',
    defaults: {
      type: 'docker-image',
      image: 'nextcloud',
      imageTag: 'latest',
      ports: [{ containerPort: 80, protocol: 'TCP' }],
      envVars: [
        { key: 'NEXTCLOUD_ADMIN_USER', value: 'admin' },
        { key: 'NEXTCLOUD_ADMIN_PASSWORD', value: 'changeme' },
      ],
      volumes: [
        { name: 'data', mountPath: '/var/www/html', size: '20Gi' },
      ],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'minio',
    name: 'MinIO',
    description: 'Stockage objet S3-compatible haute performance.',
    category: 'storage',
    icon: '🗄️',
    docs: 'https://hub.docker.com/r/minio/minio',
    defaults: {
      type: 'docker-image',
      image: 'minio/minio',
      imageTag: 'latest',
      ports: [{ containerPort: 9001, protocol: 'TCP' }],
      envVars: [
        { key: 'MINIO_ROOT_USER', value: 'admin' },
        { key: 'MINIO_ROOT_PASSWORD', value: 'changeme123' },
      ],
      volumes: [{ name: 'data', mountPath: '/data', size: '20Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  // ── Databases ─────────────────────────────────────────────────────────────
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Base de données relationnelle open-source avancée.',
    category: 'database',
    icon: '🐘',
    docs: 'https://hub.docker.com/_/postgres',
    requiredEnv: ['POSTGRES_PASSWORD'],
    defaults: {
      type: 'docker-image',
      image: 'postgres',
      imageTag: '16-alpine',
      ports: [{ containerPort: 5432, protocol: 'TCP' }],
      envVars: [
        { key: 'POSTGRES_USER', value: 'postgres' },
        { key: 'POSTGRES_PASSWORD', value: 'changeme' },
        { key: 'POSTGRES_DB', value: 'app' },
      ],
      volumes: [{ name: 'data', mountPath: '/var/lib/postgresql/data', size: '10Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Base de données relationnelle MySQL.',
    category: 'database',
    icon: '🐬',
    docs: 'https://hub.docker.com/_/mysql',
    requiredEnv: ['MYSQL_ROOT_PASSWORD'],
    defaults: {
      type: 'docker-image',
      image: 'mysql',
      imageTag: '8.0',
      ports: [{ containerPort: 3306, protocol: 'TCP' }],
      envVars: [
        { key: 'MYSQL_ROOT_PASSWORD', value: 'changeme' },
        { key: 'MYSQL_DATABASE', value: 'app' },
        { key: 'MYSQL_USER', value: 'app' },
        { key: 'MYSQL_PASSWORD', value: 'changeme' },
      ],
      volumes: [{ name: 'data', mountPath: '/var/lib/mysql', size: '10Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'Cache et store de données en mémoire.',
    category: 'database',
    icon: '⚡',
    docs: 'https://hub.docker.com/_/redis',
    defaults: {
      type: 'docker-image',
      image: 'redis',
      imageTag: '7-alpine',
      ports: [{ containerPort: 6379, protocol: 'TCP' }],
      envVars: [],
      volumes: [{ name: 'data', mountPath: '/data', size: '2Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Base de données orientée documents.',
    category: 'database',
    icon: '🍃',
    docs: 'https://hub.docker.com/_/mongo',
    defaults: {
      type: 'docker-image',
      image: 'mongo',
      imageTag: '7',
      ports: [{ containerPort: 27017, protocol: 'TCP' }],
      envVars: [
        { key: 'MONGO_INITDB_ROOT_USERNAME', value: 'admin' },
        { key: 'MONGO_INITDB_ROOT_PASSWORD', value: 'changeme' },
      ],
      volumes: [{ name: 'data', mountPath: '/data/db', size: '10Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  // ── Devops / monitoring ───────────────────────────────────────────────────
  {
    id: 'portainer',
    name: 'Portainer',
    description: 'Interface de gestion Docker / Kubernetes.',
    category: 'devops',
    icon: '🐳',
    docs: 'https://hub.docker.com/r/portainer/portainer-ce',
    defaults: {
      type: 'docker-image',
      image: 'portainer/portainer-ce',
      imageTag: 'latest',
      ports: [{ containerPort: 9000, protocol: 'TCP' }],
      envVars: [],
      volumes: [{ name: 'data', mountPath: '/data', size: '2Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Dashboards de métriques et observabilité.',
    category: 'monitoring',
    icon: '📈',
    docs: 'https://hub.docker.com/r/grafana/grafana',
    defaults: {
      type: 'docker-image',
      image: 'grafana/grafana',
      imageTag: 'latest',
      ports: [{ containerPort: 3000, protocol: 'TCP' }],
      envVars: [
        { key: 'GF_SECURITY_ADMIN_PASSWORD', value: 'changeme' },
      ],
      volumes: [{ name: 'data', mountPath: '/var/lib/grafana', size: '5Gi' }],
      replicas: 1,
      ingressClass: 'traefik',
    },
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all',         label: 'Tous' },
  { id: 'web',         label: 'Web' },
  { id: 'database',    label: 'Bases de données' },
  { id: 'storage',     label: 'Stockage' },
  { id: 'monitoring',  label: 'Monitoring' },
  { id: 'devops',      label: 'DevOps' },
  { id: 'productivity',label: 'Productivité' },
] as const;
